CREATE TABLE IF NOT EXISTS tc5_police_profiles (
    id INT NOT NULL AUTO_INCREMENT,
    char_id INT NOT NULL,
    badge_number VARCHAR(32) DEFAULT NULL,
    callsign VARCHAR(32) DEFAULT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniq_char_id (char_id)
);
