CREATE TABLE IF NOT EXISTS tc5_jobs (
    char_id INT NOT NULL,
    job_name VARCHAR(50) NOT NULL,
    grade INT NOT NULL DEFAULT 0,
    onduty TINYINT(1) NOT NULL DEFAULT 1,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (char_id)
);
